apply:
  description: Applies the current Adaptive Lighting settings to lights.
  fields:
    entity_id:
      description: entity_id of the Adaptive Lighting switch.
      example: switch.adaptive_lighting_default
    lights:
      description: entity_id(s) of lights.
      example: light.bedroom_ceiling
    transition:
      description: Transition of the lights.
      example: 10
    colors_only:
      description: Only change the color of the lights and leave the brightness as is.
      example: false
    turn_on_lights:
      description: Turn on the lights that are off.
      example: false
